#!/bin/bash

# 检查当前路径下的 xmodlib.bin 文件是否存在
if [ -f "xmodlib.bin" ]; then
    # 如果文件存在，将其进行备份
    cp xmodlib.bin xmodlibcp.bin
else
    cp xmodlibcp.bin xmodlib.bin
fi

# 打开teamserver命令
if [ -x "./brute-ratel-linx64_crack" ]; then
    # echo "参考命令:"
    # echo "./Teamserver -ratel -a admin -p password -h 192.168.1.1:8443 -sc cert.pem -sk key.pem"
    ./brute-ratel-linx64_crack $*
else
    echo "错误: ./brute-ratel-linx64_crack 不存在或不可执行，无法打开GUI"
fi
